id: IDEB88BEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:20:08+00:00'
last_modified: '2022-06-10T11:07:07.082376+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1281
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F472:
      image_group_id: I1KG1283
      title: Volume 1 of blo bzang byang chub bstan pa'i sgron me rang nyid kyi mdzad
        rnam
      total_pages: 780
      order: 1
      base_file: F472.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
